### PR TITLE
Kuber144 Completed Task-1

### PR DESCRIPTION
**Pull request by Kuber144**
Issue: 1

### CODE REVIEW

**Review by Kavita-Dhamot — CHANGES_REQUESTED** [review]
You have used textView in place of EditTextView  where we have to enter our name and age.

**Comment by Kuber144** [comment]
This was a problem in my phone maam. I have uploaded a gif showing the working of my app in my repo with the edittext.
https://github.com/Kuber144/APKmnth_AppD_Task1

**Comment by Kavita-Dhamot** [comment]
In the future don't use textColorHint actually cause it's quite confusing for the user. Anyways I'll merge your PR.

**Comment by Kuber144** [comment]
ok maam, will keep it in mind

**Pull request merged**
