### PR TITLE
Complete Task 1

### PR DESCRIPTION
**Pull request by Himanshu276330**
Issue: 1

### CODE REVIEW

**Comment by Himanshu276330** [comment]
and1

**Comment by Himanshu276330** [comment]
and2

**Comment by Himanshu276330** [comment]
My repo->
https://github.com/Himanshu276330/AppD-Task1/tree/himanshu-task1

Activity_main.xml -->
https://github.com/Himanshu276330/AppD-Task1/blob/himanshu-task1/app/src/main/res/layout/activity_main.xml

Apk file direct link ->
https://github.com/Himanshu276330/AppD-Task1/tree/himanshu-task1/App-file-ready-to-install

**Review by Kavita-Dhamot — CHANGES_REQUESTED** [review]
You have used constraint layout whereas we told yesterday to use Linear Layout. Also you have to attach your image, not Geekhaven img.

**Comment by Himanshu276330** [comment]
I update to linear layou
demo2
t

**Comment by Himanshu276330** [comment]
Mam changes Kar diya

**Pull request merged**
